name: Build, Publish, and Deploy

on:
  push:
    branches:
      - main
      - dev-Backend
  pull_request:
    branches:
      - main
      - dev-Backend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: tony203/iupi

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List files for debugging
        run: ls -R   # Muestra toda la estructura de archivos para verificar dónde está el requirements.txt

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Check if requirements.txt exists
        run: |
          if [ -f "model-2/fintech_recommender/requirements.txt" ]; then
            echo "✅ El archivo requirements.txt fue encontrado."
          else
            echo "❌ ERROR: El archivo requirements.txt NO existe."
            exit 1
          fi

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r model-2/fintech_recommender/requirements.txt 

      - name: Run migrations
        run: |
          python model-2/fintech_recommender/manage.py migrate  

      - name: Collect static files
        run: |
          python model-2/fintech_recommender/manage.py collectstatic --noinput  

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:latest model-2/fintech_recommender 
          docker push ${{ env.IMAGE_NAME }}:latest

      - name: Logout from Docker Hub
        run: docker logout
